theme: jekyll-theme-slate
title: DVision Media Agency
description: Digital Media Agency, Social Media Agency, Internet Marketing
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jemoji
exclude:
  - kb/_template.md
